server:
  port: 43897
spring:
  datasource:
    url: jdbc:mysql://154.8.165.216:3307/martyn?useSSL=false&serverTimezone=UTC
    username: root
    password: luo123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
